name: publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-test:
    uses: jotelha/dtool-framework-workflows/.github/workflows/dtool-lookup-framewok-generic-container-image-publication.yml@master
    with:
      image: jotelha/dtool-token-generator-ldap
      docker_file: ./compose/production/token_generator_ldap/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
